add all_ target, improve check output

diff --git a/ci/Makefile.jenkins b/ci/Makefile.jenkins
--- a/ci/Makefile.jenkins
+++ b/ci/Makefile.jenkins
@@ -200,18 +200,14 @@ check_deps_prepare:
 	cd ci-build/check && unzip xgboost4j-native-$(OS)_$(BACKEND)$(OMP_VERSION).jar
 	cd ci-build/check && chmod +x lib/$(OS)_64/libxgboost4j*
 check_deps_linux: check_deps_prepare
-	ldd ci-build/check/lib/$(OS)_64/libxgboost4j_$(BACKEND).so > ci-build/check/ldd-check-$(OS)-$(DISTRO)-$(BACKEND)$(OMP_VERSION).log 2>&1
+	ldd ci-build/check/lib/$(OS)_64/libxgboost4j_$(BACKEND).so | tee ci-build/check/ldd-check-$(OS)-$(DISTRO)-$(BACKEND)$(OMP_VERSION).log 2>&1
 ifneq (,$(findstring not found,$(shell cat ci-build/check/ldd-check-$(OS)-$(DISTRO)-$(BACKEND)$(OMP_VERSION).log 2> /dev/null)))
-	echo "ldd check failed! Please check the following output:" && \
-	ldd ci-build/check/lib/$(OS)_64/libxgboost4j_$(BACKEND).so && \
-	exit 1
+	echo "ldd check failed! Please check the output" && exit 1
 endif
 check_deps_osx: check_deps_prepare
-	otool -L ci-build/check/lib/$(OS)_64/libxgboost4j_$(BACKEND).dylib > ci-build/check/otool-check-$(OS)-$(DISTRO)-$(BACKEND)$(OMP_VERSION).log 2>&1
+	otool -L ci-build/check/lib/$(OS)_64/libxgboost4j_$(BACKEND).dylib | tee ci-build/check/otool-check-$(OS)-$(DISTRO)-$(BACKEND)$(OMP_VERSION).log 2>&1
 ifneq (,$(findstring not found,$(shell cat ci-build/check/otool-check-$(OS)-$(DISTRO)-$(BACKEND)$(OMP_VERSION).log 2> /dev/null)))
-	echo "otool check failed! Please check the following output:" && \
-	otool -L ci-build/check/lib/$(OS)_64/libxgboost4j_$(BACKEND).dylib && \
-	exit 1
+	echo "otool check failed! Please check the output-" && exit 1
 endif
 
 jar_package_%_in_docker:
@@ -436,3 +432,6 @@ osx_whl%:
 
 osx_check_minimal:
 	$(MAKE) -f $(THIS_FILE) BACKEND=minimal check_deps_osx
+
+all_%:
+	$(MAKE) -f $(THIS_FILE) TARGET_OS=linux mrproper build_$*_in_docker whls_$*_in_docker jar_$*_in_docker jar_package_$*_in_docker
